<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.2.129
     Generated on:       10/20/2016 9:07 PM
     Generated by:       Alex Monroe
     Organization:       SignPost Coffee, LLC
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2016
#>

	<#	
		===========================================================================
		 Created with: 	SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.2.129
		 Created on:   	10/20/2016 3:04 PM
		 Created by:   	Alex Monroe
		 Organization: 	The Christian Broadcasting Network, Inc.
		 Filename:     	CbnSignCode.psm1
		-------------------------------------------------------------------------
		 Module Name: CbnSignCode
		===========================================================================
	#>
	
	# Code Signing
	function Set-DigitalSignature {
		[CmdletBinding()]
	    param (
			[Parameter(Mandatory=$true, Position=0, ValueFromPipeline=$true)]
			[string[]]
			$FilePath
		)
	
	    begin {
	        $certificate = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert
	        if (-not $certificate) { Write-Error 'Error locating code signing certificate.' }
	
	        $timestampServer = 'http://timestamp.globalsign.com/scripts/timstamp.dll'
	    }
	
	    process {
	        foreach ($file in $FilePath) {
	            Write-Verbose "Signing $file"
	            Set-AuthenticodeSignature $file -Certificate $certificate -TimestampServer $timestampServer
	        }
	    }
	
	    end {
	        Write-Verbose 'Set-DigitalSignature complete'
	    }
	}
	
	
	Export-ModuleMember -Function Set-DigitalSignature