<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.2.129
     Generated on:       10/21/2016 8:50 AM
     Generated by:       Alex Monroe
     Organization:       The Christian Broadcasting Network, Inc.
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2016
#>

	<#
		CbnFlavor PowerShell Module
	#>
	
	function Add-Flavor {
	<#
		.SYNOPSIS
			Adds a bit of flavor to your PowerShell experience.
		
		.DESCRIPTION
			The Add-Flavor cmdlets helps to add a bit of flavor to your
			PowerShell experience. It adds a bit of spice, it helps to kick
			up a notch.
		
		.PARAMETER Flavor
			[Optional] Select the spice MI, SW, MB, CI, or BHC. The
			default spice, if not otherwise specified, is MI.
		
		.PARAMETER AsJob
			Sometimes you need to add some flavor, but keep on moving.
		
		.EXAMPLE
			PS C:\> Add-Flavor -Flavor SW -AsJob
		
		.NOTES
			Names, characters, businesses, places, events and incidents are
			either the products of the author's imagination or used in a
			fictitious manner. Any resemblance to actual persons, living or
			dead, or actual events is purely coincidental.
	#>
	    param (
	        [ValidateSet('MI','SW','MB','CI','BHC')] 
	        [Parameter(Position=0)]
	        [string]$Flavor = 'MI',
	
	        [switch]$AsJob
	    )
	
	    $flavorList = @{}
	
	    $flavorList.Add('MI', $null)
	    $flavorList.Item('MI') = {
	        [console]::beep(784,150) 
	        [System.Threading.Thread]::Sleep(300) 
	        [console]::beep(784,150) 
	        [System.Threading.Thread]::Sleep(300) 
	        [console]::beep(932,150) 
	        [System.Threading.Thread]::Sleep(150) 
	        [console]::beep(1047,150) 
	        [System.Threading.Thread]::Sleep(150) 
	        [console]::beep(784,150) 
	        [System.Threading.Thread]::Sleep(300) 
	        [console]::beep(784,150) 
	        [System.Threading.Thread]::Sleep(300) 
	        [console]::beep(699,150) 
	        [System.Threading.Thread]::Sleep(150) 
	        [console]::beep(740,150) 
	        [System.Threading.Thread]::Sleep(150) 
	        [console]::beep(784,150) 
	        [System.Threading.Thread]::Sleep(300) 
	        [console]::beep(784,150) 
	        [System.Threading.Thread]::Sleep(300) 
	        [console]::beep(932,150) 
	        [System.Threading.Thread]::Sleep(150) 
	        [console]::beep(1047,150) 
	        [System.Threading.Thread]::Sleep(150) 
	        [console]::beep(784,150) 
	        [System.Threading.Thread]::Sleep(300) 
	        [console]::beep(784,150) 
	        [System.Threading.Thread]::Sleep(300) 
	        [console]::beep(699,150) 
	        [System.Threading.Thread]::Sleep(150) 
	        [console]::beep(740,150) 
	        [System.Threading.Thread]::Sleep(150) 
	        [console]::beep(932,150) 
	        [console]::beep(784,150) 
	        [console]::beep(587,1200) 
	        [System.Threading.Thread]::Sleep(75) 
	        [console]::beep(932,150) 
	        [console]::beep(784,150) 
	        [console]::beep(554,1200) 
	        [System.Threading.Thread]::Sleep(75) 
	        [console]::beep(932,150) 
	        [console]::beep(784,150) 
	        [console]::beep(523,1200) 
	        [System.Threading.Thread]::Sleep(150) 
	        [console]::beep(466,150) 
	        [console]::beep(523,150)
	    }
	
	    $flavorList.Add('SW', $null)
	    $flavorList.Item('SW') = {
	        [console]::beep(440,500) 
	        [console]::beep(440,500) 
	        [console]::beep(440,500) 
	        [console]::beep(349,350) 
	        [console]::beep(523,150) 
	        [console]::beep(440,500) 
	        [console]::beep(349,350) 
	        [console]::beep(523,150) 
	        [console]::beep(440,1000) 
	        [console]::beep(659,500) 
	        [console]::beep(659,500) 
	        [console]::beep(659,500) 
	        [console]::beep(698,350) 
	        [console]::beep(523,150) 
	        [console]::beep(415,500) 
	        [console]::beep(349,350) 
	        [console]::beep(523,150) 
	        [console]::beep(440,1000)
	    }
	
	    $flavorList.Add('MB', $null)
	    $flavorList.Item('MB') = {
	        [System.Console]::Beep(659, 125);
	        [System.Console]::Beep(659, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(659, 125);
	        [System.Threading.Thread]::Sleep(167);
	        [System.Console]::Beep(523, 125);
	        [System.Console]::Beep(659, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(784, 125);
	        [System.Threading.Thread]::Sleep(375);
	        [System.Console]::Beep(392, 125);
	        [System.Threading.Thread]::Sleep(375);
	        [System.Console]::Beep(523, 125);
	        [System.Threading.Thread]::Sleep(250);
	        [System.Console]::Beep(392, 125);
	        [System.Threading.Thread]::Sleep(250);
	        [System.Console]::Beep(330, 125);
	        [System.Threading.Thread]::Sleep(250);
	        [System.Console]::Beep(440, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(494, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(466, 125);
	        [System.Threading.Thread]::Sleep(42);
	        [System.Console]::Beep(440, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(392, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(659, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(784, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(880, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(698, 125);
	        [System.Console]::Beep(784, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(659, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(523, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(587, 125);
	        [System.Console]::Beep(494, 125);
	        [System.Threading.Thread]::Sleep(125);
	        [System.Console]::Beep(523, 125);
	    }
	
	    $flavorList.Add('CI', $null)
	    $flavorList.Item('CI') = {
	        [console]::beep(900,400)
	        [console]::beep(1000,400)
	        [console]::beep(800,400)
	        [console]::beep(400,400)
	        [console]::beep(600,1600)
	    }
	
	    $flavorList.Add('BHC', $null)
	    $flavorList.Item('BHC') = {
	        [console]::beep(659,460)
	        [console]::beep(784,340)
	        [console]::beep(659,230)
	        [console]::beep(659,110)
	        [console]::beep(880,230)
	        [console]::beep(659,230)
	        [console]::beep(587,230)
	        [console]::beep(659,460)
	        [console]::beep(988,340)
	        [console]::beep(659,230)
	        [console]::beep(659,110)
	        [console]::beep(1047,230)
	        [console]::beep(988,230)
	        [console]::beep(784,230)
	        [console]::beep(659,230)
	        [console]::beep(988,230)
	        [console]::beep(1318,230)
	        [console]::beep(659,110)
	        [console]::beep(587,230)
	        [console]::beep(587,110)
	        [console]::beep(494,230)
	        [console]::beep(740,230)
	        [console]::beep(659,700)
	    }
	
	    if ($AsJob) {
	        Start-Job -ScriptBlock $flavorList.Item($Flavor)
	    } else {
	        Invoke-Command -ScriptBlock $flavorList.Item($Flavor)
	    }
	}
	
	Export-ModuleMember -Function Add-Flavor
	