<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.3.131
     Generated on:       1/12/2017 10:39 AM
     Generated by:       Alex Monroe
     Organization:       The Christian Broadcasting Network, Inc.
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2016
#>

<#	
	===========================================================================
	 Created with: 	SAPIEN Technologies, Inc., PowerShell Studio 2016 v5.3.131
	 Created on:   	1/12/2017 9:38 AM
	 Created by:   	Alex Monroe
	 Organization: 	The Christian Broadcasting Network, Inc.
	 Filename:     	CbnSwisPowerShell.psm1
	-------------------------------------------------------------------------
	 Module Name: CbnSwisPowerShell
	===========================================================================
#>

# Unload the SwisSnapin if loaded
if (Get-PSSnapin -Name SwisSnapin -ErrorAction SilentlyContinue) {
	Remove-PSSnapin -Name SwisSnapin
}

# Load the CbnSwisPowerShell modules
Import-Module -Name "$PSScriptRoot\log4net.dll" -Scope Global
Import-Module -Name "$PSScriptRoot\ScintillaNet.dll" -Scope Global
Import-Module -Name "$PSScriptRoot\Security.Cryptography.dll" -Scope Global
Import-Module -Name "$PSScriptRoot\SolarWinds.Logging.dll" -Scope Global
Import-Module -Name "$PSScriptRoot\SolarWinds.SDK.Swis.Contract.dll" -Scope Global
Import-Module -Name "$PSScriptRoot\SwisPowerShell.dll"

Export-ModuleMember -Cmdlet Connect-Swis, Get-SwisObject, Get-SwisData, Invoke-SwisVerb, `
	New-SwisObject, Remove-SwisObject, Set-SwisObject
